version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: deps
    container_name: intranet-backend-dev
    restart: unless-stopped
    ports:
      - '3001:3001'
      - '9229:9229'  # Debug port
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
    command: npm run start:debug

